using KazistovVvUI;

namespace KazistovVvFeatures
{
    /// <summary>
    /// ЛОКАЛИЗАЦИЯ ЭТАПОВ 7–12 (ограничения на waypoints, планирование с ограничениями,
    /// калибровочный мастер, калькулятор нагрузки, экспорт в языки роботов, импорт URDF/STEP).
    ///
    /// Формат и правила те же, что у <see cref="KvLocExtra"/> (см. его комментарий):
    /// таблица «ключ + 7 языков» (RU / EN / ZH / ES / DE / FR / JA), регистрация во время
    /// работы через `KvLoc.AddRuntimeStrings`, внешние словари остаются ГЛАВНЫМИ
    /// (пишутся только отсутствующие ключи), цепочка fallback «текущий язык → английский →
    /// русский текст из кода» сохраняется полностью.
    /// </summary>
    public static class KvLocExtra2
    {
        private static bool installed;
        private static int registered;

        /// <summary>Сколько строк добавлено модулем (диагностика).</summary>
        public static int RegisteredCount { get { return registered; } }

        /// <summary>ФИКС 13: сколько строк в таблице модуля (для теста покрытия 7 языков).</summary>
        public static int RowCount { get { return Rows.Length; } }

        /// <summary>ФИКС 13: ключ строки таблицы по номеру (для теста покрытия 7 языков).</summary>
        public static string KeyAt(int index)
        {
            if (index < 0 || index >= Rows.Length) return "";
            return Rows[index] != null && Rows[index].Length > 0 ? Rows[index][0] : "";
        }

        /// <summary>Перевод по ключу (fallback — русский текст из кода).</summary>
        public static string T(string key, string fallback)
        {
            return KvLoc.T(key, fallback);
        }

        /// <summary>Перевод с подстановкой: {0}, {1} — как в string.Format.</summary>
        public static string F(string key, string fallback, params object[] args)
        {
            string pattern = KvLoc.T(key, fallback);
            try { return string.Format(pattern, args); }
            catch { return pattern; }
        }

        /// <summary>Зарегистрировать строки (вызывает хаб этапов 7–12 один раз).</summary>
        public static void Install()
        {
            if (installed) return;
            installed = true;

            int count = 0;
            for (int r = 0; r < Rows.Length; r++)
            {
                string[] row = Rows[r];
                if (row == null || row.Length < 1 + KvLocExtra.Codes.Length) continue;
                string key = row[0];
                if (string.IsNullOrEmpty(key)) continue;
                if (KvLoc.Has(key)) continue;      // словарь интерфейса главнее

                bool wrote = false;
                for (int c = 0; c < KvLocExtra.Codes.Length; c++)
                {
                    string text = row[c + 1];
                    if (string.IsNullOrEmpty(text)) continue;
                    KvLoc.AddRuntimeStrings(KvLocExtra.Codes[c], key, text);
                    wrote = true;
                }
                if (wrote) count++;
            }

            registered = count;
            UnityEngine.Debug.Log("[Loc] строки этапов 7–12 зарегистрированы: " + count +
                                  " · всего в словарях: " + KvLoc.TotalStrings);
        }

        // ================================================================== таблица строк

        private static readonly string[][] Rows =
        {
            // ---------------------------------------------------------- ЭТАП 7: ограничения waypoints
            Row("wp.limits",
                "Ограничения точки", "Waypoint constraints", "路点约束", "Restricciones del punto",
                "Wegpunkt-Vorgaben", "Contraintes du point", "ウェイポイント制約"),
            Row("wp.orient",
                "Требуемая ориентация TCP", "Required TCP orientation", "要求的 TCP 姿态",
                "Orientación TCP requerida", "Geforderte TCP-Orientierung",
                "Orientation TCP requise", "要求される TCP 姿勢"),
            Row("wp.orient.hint",
                "Направление оси инструмента в мире: X / Y / Z и знак",
                "Tool axis direction in world: X / Y / Z and sign",
                "工具轴在世界中的方向：X / Y / Z 与符号",
                "Dirección del eje de la herramienta: X / Y / Z y signo",
                "Werkzeugachse in der Welt: X / Y / Z und Vorzeichen",
                "Direction de l'axe outil : X / Y / Z et signe",
                "工具軸のワールド方向：X / Y / Z と符号"),
            Row("wp.orient.tol",
                "Допуск ориентации, °", "Orientation tolerance, °", "姿态公差 °",
                "Tolerancia de orientación, °", "Orientierungstoleranz, °",
                "Tolérance d'orientation, °", "姿勢公差 °"),
            Row("wp.speed",
                "Ограничение скорости", "Speed limit", "速度限制", "Límite de velocidad",
                "Geschwindigkeitsgrenze", "Limite de vitesse", "速度制限"),
            Row("wp.speed.value",
                "Макс. скорость TCP в точке, м/с", "Max TCP speed at the point, m/s",
                "该点 TCP 最大速度 m/s", "Velocidad TCP máx. en el punto, m/s",
                "Max. TCP-Geschwindigkeit am Punkt, m/s",
                "Vitesse TCP max. au point, m/s", "点での TCP 最大速度 m/s"),
            Row("wp.detour",
                "Обязательный обход препятствия", "Mandatory obstacle detour",
                "必须绕开障碍", "Desvío obligatorio del obstáculo",
                "Pflicht-Umfahrung des Hindernisses", "Contournement obligatoire",
                "障害物の迂回を必須にする"),
            Row("wp.detour.radius",
                "Радиус окрестности препятствия, м", "Obstacle radius, m",
                "障碍半径 m", "Radio del obstáculo, m", "Hindernisradius, m",
                "Rayon de l'obstacle, m", "障害物半径 m"),
            Row("wp.detour.point",
                "Взять центр препятствия из точки прицела",
                "Take obstacle center from the aim point",
                "从瞄准点取障碍中心", "Tomar el centro del obstáculo desde la mira",
                "Hinderniszentrum aus dem Zielpunkt übernehmen",
                "Prendre le centre de l'obstacle depuis le viseur",
                "照準点から障害物中心を取得"),
            Row("wp.pause",
                "Пауза в точке", "Pause at the point", "在该点暂停", "Pausa en el punto",
                "Pause am Punkt", "Pause au point", "その点で一時停止"),
            Row("wp.pause.value",
                "Длительность паузы, с", "Pause duration, s", "暂停时长 s",
                "Duración de la pausa, s", "Pausendauer, s", "Durée de la pause, s", "停止時間 s"),
            Row("wp.apply",
                "Применить ограничения", "Apply constraints", "应用约束", "Aplicar restricciones",
                "Vorgaben anwenden", "Appliquer les contraintes", "制約を適用"),
            Row("wp.clear",
                "Снять ограничения", "Clear constraints", "清除约束", "Quitar restricciones",
                "Vorgaben entfernen", "Retirer les contraintes", "制約を解除"),
            Row("wp.none",
                "Промежуточных точек нет: добавьте waypoint в точке прицела (Z + ЛКМ, затем кнопка)",
                "No waypoints: add one at the aim point (Z + LMB, then the button)",
                "没有路点：在瞄准点添加（Z + 左键，然后按钮）",
                "Sin puntos: añada uno en la mira (Z + clic y el botón)",
                "Keine Wegpunkte: am Zielpunkt hinzufügen (Z + LMB, dann Taste)",
                "Aucun point : ajoutez-en un au viseur (Z + clic puis bouton)",
                "ウェイポイントなし：照準点で追加（Z + 左クリック→ボタン）"),
            Row("wp.status",
                "Ограничения точки", "Waypoint constraints", "路点约束", "Restricciones",
                "Vorgaben", "Contraintes", "制約"),
            Row("wp.select",
                "Выберите точку в списке (кнопки ◀ ▶) или добавьте новую",
                "Select a waypoint in the list (buttons ◀ ▶) or add a new one",
                "请在列表中选择路点（◀ ▶）或新增",
                "Elija un punto en la lista (botones ◀ ▶) o añada uno",
                "Wählen Sie einen Wegpunkt (Tasten ◀ ▶) oder fügen Sie einen hinzu",
                "Choisissez un point (boutons ◀ ▶) ou ajoutez-en un",
                "リストから路点を選ぶ（◀ ▶）か新規追加してください"),
            Row("wp.orient.now",
                "Ориентация ← как сейчас", "Orientation ← current", "姿态 ← 当前",
                "Orientación ← actual", "Orientierung ← aktuell", "Orientation ← actuelle",
                "姿勢 ← 現在"),
            Row("wp.orient.dir",
                "Направление оси инструмента", "Tool axis direction", "工具轴方向",
                "Dirección del eje", "Werkzeugachsenrichtung", "Direction de l'axe",
                "工具軸の方向"),
            Row("wp.solved",
                "поза с ограничением найдена", "constrained pose solved", "已求出受限姿态",
                "pose con restricción resuelta", "vorgabentreue Pose gefunden",
                "pose contrainte trouvée", "制約付き姿勢を算出"),
            Row("wp.orient.fail",
                "ориентация не достигнута", "orientation not reached", "未达到要求的姿态",
                "orientación no alcanzada", "Orientierung nicht erreicht",
                "orientation non atteinte", "姿勢に到達できません"),
            Row("wp.detour.fail",
                "обход препятствия не найден", "detour not found", "未找到绕行路径",
                "no se encontró desvío", "Umfahrung nicht gefunden",
                "contournement introuvable", "迂回経路が見つかりません"),
            Row("wp.speed.applied",
                "профиль времени ограничен скоростью в точке",
                "time profile limited by the waypoint speed",
                "时间曲线受该点速度限制",
                "perfil de tiempo limitado por la velocidad del punto",
                "Zeitprofil durch Punktgeschwindigkeit begrenzt",
                "プロファイルはその点の速度で制限",
                "時間プロファイルをその点の速度で制限"),
            Row("wp.pause.done",
                "в маршрут добавлена пауза", "pause inserted into the route", "路线中加入暂停",
                "pausa añadida a la ruta", "Pause in die Route eingefügt",
                "pause insérée dans l'itinéraire", "ルートに停止を追加"),
            Row("cmd.wp.orient",
                "Ориентация waypoint", "Waypoint orientation", "路点姿态", "Orientación del waypoint",
                "Wegpunkt-Orientierung", "Orientation du point", "ウェイポイント姿勢"),
            Row("cmd.wp.orient.desc",
                "Задать требуемое направление оси инструмента в выбранной промежуточной точке",
                "Set the required tool axis direction at the selected waypoint",
                "为所选路点设置工具轴方向",
                "Fijar la dirección del eje de la herramienta en el punto seleccionado",
                "Geforderte Werkzeugachse am gewählten Wegpunkt setzen",
                "Définir l'axe outil requis au point sélectionné",
                "選択したウェイポイントの工具軸方向を設定"),
            Row("cmd.wp.speed",
                "Скорость waypoint", "Waypoint speed", "路点速度", "Velocidad del waypoint",
                "Wegpunkt-Geschwindigkeit", "Vitesse du point", "ウェイポイント速度"),
            Row("cmd.wp.speed.desc",
                "Ограничить скорость TCP в выбранной промежуточной точке",
                "Limit TCP speed at the selected waypoint",
                "限制所选路点的 TCP 速度",
                "Limitar la velocidad TCP en el punto seleccionado",
                "TCP-Geschwindigkeit am gewählten Wegpunkt begrenzen",
                "Limiter la vitesse TCP au point sélectionné",
                "選択したウェイポイントの TCP 速度を制限"),
            Row("cmd.wp.detour",
                "Обход препятствия (waypoint)", "Obstacle detour (waypoint)",
                "绕开障碍（路点）", "Desvío del obstáculo (waypoint)",
                "Hindernis umfahren (Wegpunkt)", "Contourner l'obstacle (point)",
                "障害物の迂回（ウェイポイント）"),
            Row("cmd.wp.detour.desc",
                "Обязать маршрут обходить окрестность препятствия у выбранной точки",
                "Force the route to detour around the obstacle near the selected waypoint",
                "强制路线绕开所选路点附近的障碍",
                "Obligar a la ruta a rodear el obstáculo cerca del punto",
                "Route muss das Hindernis am Wegpunkt umfahren",
                "Forcer l'itinéraire à contourner l'obstacle près du point",
                "選択した路点付近の障害物を迂回させる"),
            Row("cmd.wp.pause",
                "Пауза waypoint", "Waypoint pause", "路点暂停", "Pausa del waypoint",
                "Wegpunkt-Pause", "Pause du point", "ウェイポイント停止"),
            Row("cmd.wp.pause.desc",
                "Остановиться и подождать в выбранной промежуточной точке",
                "Stop and wait at the selected waypoint",
                "在所选路点停止等待",
                "Detenerse y esperar en el punto seleccionado",
                "Am gewählten Wegpunkt anhalten und warten",
                "S'arrêter et attendre au point sélectionné",
                "選択したウェイポイントで停止して待機"),
            Row("cmd.wp.clear",
                "Снять ограничения waypoint", "Clear waypoint constraints", "清除路点约束",
                "Quitar restricciones del waypoint", "Wegpunkt-Vorgaben entfernen",
                "Retirer les contraintes du point", "ウェイポイント制約を解除"),
            Row("cmd.wp.clear.desc",
                "Вернуть выбранной промежуточной точке обычное поведение (без ограничений)",
                "Reset the selected waypoint to plain behaviour (no constraints)",
                "将所选路点恢复为无约束",
                "Devolver el punto seleccionado al comportamiento normal",
                "Gewählten Wegpunkt ohne Vorgaben zurücksetzen",
                "Rendre au point sélectionné son comportement normal",
                "選択したウェイポイントを制約なしに戻す"),
            Row("cmd.wp.tab",
                "Ограничения waypoint (вкладка)", "Waypoint constraints (tab)",
                "路点约束（标签页）", "Restricciones del waypoint (pestaña)",
                "Wegpunkt-Vorgaben (Tab)", "Contraintes du point (onglet)",
                "ウェイポイント制約（タブ）"),
            Row("cmd.wp.tab.desc",
                "Открыть вкладку с ограничениями промежуточных точек маршрута",
                "Open the waypoint constraints tab",
                "打开路点约束标签页",
                "Abrir la pestaña de restricciones de los puntos",
                "Tab mit den Wegpunkt-Vorgaben öffnen",
                "Ouvrir l'onglet des contraintes des points",
                "ウェイポイント制約タブを開く"),

            // ---------------------------------------------------------- ЭТАП 8: планирование с ограничениями
            Row("constr.title",
                "Планирование с ограничениями", "Constrained planning", "受限规划",
                "Planificación con restricciones", "Planung mit Vorgaben",
                "Planification sous contraintes", "制約付き計画"),
            Row("constr.enable",
                "Включить ограничения планирования", "Enable constrained planning",
                "启用受限规划", "Activar planificación con restricciones",
                "Planung mit Vorgaben aktivieren", "Activer la planification contrainte",
                "制約付き計画を有効化"),
            Row("constr.mode",
                "Тип ограничения", "Constraint type", "约束类型", "Tipo de restricción",
                "Vorgabentyp", "Type de contrainte", "制約の種類"),
            Row("constr.mode.none", "нет", "none", "无", "ninguna", "keine", "aucune", "なし"),
            Row("constr.mode.vertical",
                "инструмент вертикально", "tool stays vertical", "工具保持竖直",
                "herramienta vertical", "Werkzeug senkrecht", "outil vertical", "工具を鉛直に保つ"),
            Row("constr.mode.tilt",
                "наклон не больше N°", "tilt no more than N°", "倾角不超过 N°",
                "inclinación máx. N°", "Neigung höchstens N°", "inclinaison max. N°",
                "傾きは N° 以内"),
            Row("constr.mode.lookat",
                "TCP смотрит на объект", "TCP looks at the object", "TCP 朝向目标",
                "TCP mira al objeto", "TCP zeigt auf das Objekt", "TCP vise l'objet",
                "TCP が対象を向く"),
            Row("constr.tilt",
                "Предел наклона, °", "Tilt limit, °", "倾角上限 °", "Límite de inclinación, °",
                "Neigungsgrenze, °", "Limite d'inclinaison, °", "傾き上限 °"),
            Row("constr.tolerance",
                "Допуск, °", "Tolerance, °", "公差 °", "Tolerancia, °",
                "Toleranz, °", "Tolérance, °", "公差 °"),
            Row("constr.target",
                "Объект наблюдения (из точки прицела)", "Look-at object (from the aim point)",
                "观察对象（取瞄准点）", "Objeto observado (desde la mira)",
                "Zielobjekt (aus dem Zielpunkt)", "Objet visé (depuis le viseur)",
                "注視対象（照準点から）"),
            Row("constr.axis.ref",
                "Опорное направление", "Reference direction", "参考方向", "Dirección de referencia",
                "Referenzrichtung", "Direction de référence", "基準方向"),
            Row("constr.axis.down",
                "вниз (−Y)", "down (−Y)", "向下（−Y）", "abajo (−Y)", "nach unten (−Y)",
                "vers le bas (−Y)", "下向き（−Y）"),
            Row("constr.axis.up",
                "вверх (+Y)", "up (+Y)", "向上（+Y）", "arriba (+Y)", "nach oben (+Y)",
                "vers le haut (+Y)", "上向き（+Y）"),
            Row("constr.check",
                "Проверить выбранную траекторию", "Check selected trajectory",
                "检查所选轨迹", "Comprobar la trayectoria seleccionada",
                "Gewählte Bahn prüfen", "Vérifier la trajectoire sélectionnée",
                "選択した軌道を検査"),
            Row("constr.project",
                "Привести траекторию к ограничению", "Project trajectory onto the constraint",
                "将轨迹投影到约束", "Proyectar la trayectoria a la restricción",
                "Bahn auf die Vorgabe projizieren", "Projeter la trajectoire sur la contrainte",
                "軌道を制約へ投影"),
            Row("constr.filter",
                "Отбрасывать варианты, нарушающие ограничение",
                "Discard variants that violate the constraint",
                "丢弃违反约束的方案", "Descartar variantes que violan la restricción",
                "Varianten mit Verstoß verwerfen", "Écarter les variantes non conformes",
                "制約違反の候補を除外"),
            Row("constr.status",
                "Состояние ограничения", "Constraint status", "约束状态", "Estado de la restricción",
                "Vorgabenstatus", "État de la contrainte", "制約の状態"),
            Row("constr.ok",
                "выбранная траектория удовлетворяет ограничению",
                "the selected trajectory satisfies the constraint",
                "所选轨迹满足约束", "la trayectoria cumple la restricción",
                "die gewählte Bahn erfüllt die Vorgabe", "la trajectoire respecte la contrainte",
                "選択した軌道は制約を満たします"),
            Row("constr.violated",
                "нарушений: {0} из {1} сэмплов · худший угол {2}°",
                "violations: {0} of {1} samples · worst angle {2}°",
                "违规：{0}/{1} 个采样 · 最差角度 {2}°",
                "violaciones: {0} de {1} muestras · peor ángulo {2}°",
                "Verstöße: {0} von {1} Samples · schlechtester Winkel {2}°",
                "violations : {0} sur {1} échantillons · pire angle {2}°",
                "違反：{0}/{1} サンプル · 最大角度 {2}°"),
            Row("constr.projected",
                "спроектировано сэмплов: {0} · остаток {1}°",
                "projected samples: {0} · residual {1}°",
                "已投影采样：{0} · 残差 {1}°",
                "muestras proyectadas: {0} · residuo {1}°",
                "projizierte Samples: {0} · Rest {1}°",
                "échantillons projetés : {0} · résidu {1}°",
                "投影サンプル数：{0} · 残差 {1}°"),
            Row("constr.info",
                "Ограничение проверяется на КАЖДОМ сэмпле траектории по фактической оси " +
                "инструмента (ось последнего сустава). «Привести к ограничению» пересчитывает " +
                "позы методом IK с дополнительным условием — путь остаётся у той же цели.",
                "The constraint is checked on EVERY sample using the real tool axis (last joint axis). " +
                "“Project” re-solves the poses with the extra IK condition — the goal stays the same.",
                "在每个采样上用实际工具轴（末端关节轴）检查约束。“投影”会用附加 IK 条件重解姿态，目标不变。",
                "La restricción se comprueba en CADA muestra con el eje real de la herramienta (último " +
                "eje). «Proyectar» recalcula las poses con la condición extra de IK.",
                "Die Vorgabe wird an JEDEM Sample über die echte Werkzeugachse geprüft. „Projizieren“ " +
                "löst die Posen mit der zusätzlichen IK-Bedingung neu.",
                "La contrainte est vérifiée sur CHAQUE échantillon via l'axe réel de l'outil. " +
                "« Projeter » recalcule les poses avec la condition IK supplémentaire.",
                "制約は各サンプルで実際の工具軸（最終関節軸）により検査されます。「投影」は追加の IK 条件で" +
                "姿勢を再計算します。"),
            Row("cmd.constr.toggle",
                "Ограничения планирования", "Constrained planning", "受限规划",
                "Planificación con restricciones", "Planung mit Vorgaben",
                "Planification contrainte", "制約付き計画"),
            Row("cmd.constr.toggle.desc",
                "Включить проверку ограничений (вертикальный инструмент, предел наклона, взгляд на объект)",
                "Enable constraint checking (vertical tool, tilt limit, look-at object)",
                "启用约束检查（竖直工具、倾角上限、注视对象）",
                "Activar la comprobación de restricciones",
                "Vorgabenprüfung aktivieren", "Activer la vérification des contraintes",
                "制約検査を有効化"),
            Row("cmd.constr.tab",
                "Вкладка ограничений", "Constraints tab", "约束标签页", "Pestaña de restricciones",
                "Vorgaben-Tab", "Onglet des contraintes", "制約タブ"),
            Row("cmd.constr.tab.desc",
                "Открыть окно-верстак на вкладке планирования с ограничениями",
                "Open the workbench on the constrained planning tab",
                "打开受限规划标签页", "Abrir el banco en la pestaña de restricciones",
                "Werkbank auf dem Vorgaben-Tab öffnen", "Ouvrir l'établi sur l'onglet des contraintes",
                "ワークベンチを制約付き計画タブで開く"),

            // ---------------------------------------------------------- ЭТАП 9: калибровка
            Row("calib.title",
                "Калибровочный мастер", "Calibration wizard", "标定向导", "Asistente de calibración",
                "Kalibrier-Assistent", "Assistant de calibration", "キャリブレーションウィザード"),
            Row("calib.step",
                "Шаг {0} из {1}", "Step {0} of {1}", "第 {0} 步，共 {1} 步",
                "Paso {0} de {1}", "Schritt {0} von {1}", "Étape {0} sur {1}", "ステップ {0} / {1}"),
            Row("calib.tcp",
                "Калибровка TCP (4 точки)", "TCP calibration (4 points)", "TCP 标定（4 点）",
                "Calibración TCP (4 puntos)", "TCP-Kalibrierung (4 Punkte)",
                "Calibration TCP (4 points)", "TCP キャリブレーション（4 点）"),
            Row("calib.tcp.text",
                "Наведите TCP инструмента в одну и ту же точку пространства ЧЕТЫРЬМЯ разными " +
                "ориентациями (рукой/слайдерами/пультом) и нажмите «Записать точку» после каждого " +
                "наведения. Система найдёт смещение инструмента относительно фланца.",
                "Touch the SAME point in space with the tool TCP using FOUR different orientations, " +
                "pressing “Record point” after each. The system solves the tool offset from the flange.",
                "用四种不同姿态让工具 TCP 触碰同一点，每次按“记录点”。系统将求出工具相对法兰的偏移。",
                "Toque el MISMO punto con cuatro orientaciones distintas, pulsando «Registrar punto» cada vez.",
                "Berühren Sie DENSELBEN Punkt mit VIER Orientierungen und drücken Sie jeweils „Punkt speichern“.",
                "Touchez le MÊME point avec QUATRE orientations, en pressant « Enregistrer » à chaque fois.",
                "4 つの異なる姿勢で同じ点に TCP を合わせ、毎回「点を記録」を押します。"),
            Row("calib.record",
                "Записать точку", "Record point", "记录点", "Registrar punto", "Punkt speichern",
                "Enregistrer le point", "点を記録"),
            Row("calib.reset",
                "Сбросить точки", "Reset points", "重置点", "Reiniciar puntos", "Punkte löschen",
                "Réinitialiser les points", "点をリセット"),
            Row("calib.solve",
                "Рассчитать смещение TCP", "Solve TCP offset", "计算 TCP 偏移",
                "Calcular el desplazamiento TCP", "TCP-Versatz berechnen", "Calculer le décalage TCP",
                "TCP オフセットを計算"),
            Row("calib.points",
                "Записано точек", "Points recorded", "已记录点数", "Puntos registrados",
                "Gespeicherte Punkte", "Points enregistrés", "記録した点数"),
            Row("calib.result",
                "Смещение инструмента (в системе фланца), мм",
                "Tool offset (flange frame), mm", "工具偏移（法兰坐标系）mm",
                "Desplazamiento (sistema de brida), mm", "Werkzeugversatz (Flanschsystem), mm",
                "Décalage (repère de bride), mm", "工具オフセット（フランジ座標）mm"),
            Row("calib.length",
                "Длина инструмента, мм", "Tool length, mm", "工具长度 mm", "Longitud, mm",
                "Werkzeuglänge, mm", "Longueur d'outil, mm", "工具長 mm"),
            Row("calib.residual",
                "Остаточная ошибка, мм", "Residual error, mm", "残差 mm", "Error residual, mm",
                "Restfehler, mm", "Erreur résiduelle, mm", "残差 mm"),
            Row("calib.need4",
                "Нужно 4 точки с разными ориентациями", "4 points with different orientations required",
                "需要 4 个不同姿态的点", "Se necesitan 4 puntos con orientaciones distintas",
                "4 Punkte mit unterschiedlichen Orientierungen nötig",
                "4 points d'orientations différentes requis", "異なる姿勢の点が 4 つ必要です"),
            Row("calib.base",
                "Калибровка базы робота", "Robot base calibration", "机器人基座标定",
                "Calibración de la base", "Basis-Kalibrierung", "Calibration de la base",
                "ロボットベースの校正"),
            Row("calib.base.text",
                "Коснитесь инструментом ТРЁХ точек на одной плоскости (например, столешницы) и " +
                "запишите их: система определит высоту базы над плоскостью и её наклон.",
                "Touch THREE points on one plane (e.g. the table) and record them: the system derives " +
                "the base height above the plane and its tilt.",
                "用工具触碰同一平面上的三个点并记录：系统会求出基座高度与倾斜。",
                "Toque TRES puntos de un mismo plano y regístrelos: se obtiene la altura y la inclinación.",
                "Berühren Sie DREI Punkte einer Ebene: daraus folgen Höhe und Neigung der Basis.",
                "Touchez TROIS points d'un même plan : on en déduit la hauteur et l'inclinaison.",
                "同一平面上の 3 点に触れて記録すると、高さと傾きが求まります。"),
            Row("calib.base.result",
                "База: высота {0} мм · наклон {1}° · поворот {2}°",
                "Base: height {0} mm · tilt {1}° · yaw {2}°",
                "基座：高度 {0} mm · 倾角 {1}° · 偏航 {2}°",
                "Base: altura {0} mm · inclinación {1}° · giro {2}°",
                "Basis: Höhe {0} mm · Neigung {1}° · Gierung {2}°",
                "Base : hauteur {0} mm · inclinaison {1}° · lacet {2}°",
                "ベース：高さ {0} mm · 傾き {1}° · ヨー {2}°"),
            Row("calib.camera",
                "Калибровка камеры (hand-eye)", "Camera calibration (hand-eye)",
                "相机标定（手眼）", "Calibración de cámara (hand-eye)",
                "Kamera-Kalibrierung (Hand-Auge)", "Calibration caméra (hand-eye)",
                "カメラ校正（ハンドアイ）"),
            Row("calib.camera.text",
                "Заглушка на будущее: потребуется модель крепления камеры. Сейчас сохраняется " +
                "намерение калибровки и занятое место в файле.",
                "Placeholder for the future: a camera mount model is required. For now the intent is " +
                "stored in the calibration file.",
                "预留占位：需要相机安装模型。当前仅保存标定意向。",
                "Marcador para el futuro: hace falta el modelo de montaje. Por ahora se guarda la intención.",
                "Platzhalter: ein Kamerahalterungsmodell fehlt. Derzeit wird nur die Absicht gespeichert.",
                "Emplacement réservé : le modèle de fixation manque. Seule l'intention est enregistrée.",
                "将来用のプレースホルダ：カメラ取付モデルが必要です。今は意図のみ保存します。"),
            Row("calib.save",
                "Сохранить калибровку в файл", "Save calibration to file", "保存标定到文件",
                "Guardar calibración en archivo", "Kalibrierung speichern",
                "Enregistrer la calibration", "キャリブレーションを保存"),
            Row("calib.saved",
                "калибровка сохранена", "calibration saved", "标定已保存", "calibración guardada",
                "Kalibrierung gespeichert", "calibration enregistrée", "キャリブレーションを保存しました"),
            Row("calib.apply",
                "Применить смещение к потоку (toolOffset)", "Apply offset to the flow (toolOffset)",
                "将偏移应用到流程（toolOffset）", "Aplicar el desplazamiento al flujo",
                "Versatz auf den Ablauf anwenden", "Appliquer le décalage au flux",
                "オフセットをフローに適用"),
            Row("calib.file",
                "Файл калибровки", "Calibration file", "标定文件", "Archivo de calibración",
                "Kalibrierdatei", "Fichier de calibration", "キャリブレーションファイル"),
            Row("calib.none",
                "калибровка не выполнялась", "no calibration yet", "尚未标定",
                "sin calibración", "keine Kalibrierung", "pas de calibration", "未校正"),
            Row("cmd.calib.tab",
                "Калибровочный мастер", "Calibration wizard", "标定向导", "Asistente de calibración",
                "Kalibrier-Assistent", "Assistant de calibration", "キャリブレーション"),
            Row("cmd.calib.tab.desc",
                "Пошаговая калибровка TCP (4 точки), базы робота и камеры (заглушка); сохранение в файл",
                "Step-by-step calibration: TCP (4 points), robot base, camera (placeholder); saved to file",
                "分步标定：TCP（4 点）、基座、相机（占位）；保存到文件",
                "Calibración paso a paso: TCP, base, cámara; guardado en archivo",
                "Schrittweise Kalibrierung: TCP, Basis, Kamera; Speichern in Datei",
                "Calibration pas à pas : TCP, base, caméra ; enregistrement",
                "段階的校正：TCP・ベース・カメラ。ファイル保存"),

            // ---------------------------------------------------------- ЭТАП 10: нагрузка
            Row("payload.title",
                "Калькулятор нагрузки", "Payload calculator", "负载计算器", "Calculadora de carga",
                "Nutzlast-Rechner", "Calculateur de charge", "ペイロード計算"),
            Row("payload.now",
                "Максимальная нагрузка в текущей позе, кг",
                "Max payload in the current pose, kg", "当前姿态的最大负载 kg",
                "Carga máxima en la pose actual, kg", "Max. Nutzlast in der aktuellen Pose, kg",
                "Charge max. dans la pose actuelle, kg", "現在の姿勢での最大ペイロード kg"),
            Row("payload.rating",
                "Номинальный момент суставов, Н·м", "Rated joint torque, N·m",
                "关节额定力矩 N·m", "Par nominal de ejes, N·m", "Nennmoment der Gelenke, N·m",
                "Couple nominal des axes, N·m", "関節定格トルク N·m"),
            Row("payload.safety",
                "Коэффициент запаса", "Safety factor", "安全系数", "Factor de seguridad",
                "Sicherheitsfaktor", "Coefficient de sécurité", "安全率"),
            Row("payload.graph",
                "Нагрузка от расстояния от базы", "Payload vs distance from the base",
                "负载与基座距离的关系", "Carga frente a la distancia", "Nutzlast über dem Abstand",
                "Charge selon la distance", "ベースからの距離とペイロード"),
            Row("payload.distance",
                "Расстояние от базы, м", "Distance from base, m", "距基座距离 m",
                "Distancia desde la base, m", "Abstand von der Basis, m",
                "Distance depuis la base, m", "ベースからの距離 m"),
            Row("payload.limit",
                "Ограничивающий сустав", "Limiting joint", "限制关节", "Eje limitante",
                "Limitierendes Gelenk", "Axe limitant", "制限している関節"),
            Row("payload.info",
                "Оценка: момент груза считается по фактическим плечам звеньев (узлы кинематики) " +
                "и номинальным моментам суставов, с учётом массы звеньев и коэффициента запаса. " +
                "Это инженерная оценка для планирования, а не паспортный расчёт.",
                "Estimate: payload torque is computed from the real link lever arms (kinematic nodes) " +
                "and rated joint torques, including link masses and the safety factor. Engineering " +
                "estimate for planning, not a datasheet figure.",
                "估算：负载力矩按实际连杆臂（运动学节点）与关节额定力矩计算，含连杆质量与安全系数。" +
                "这是规划用的工程估算，不是出厂数据。",
                "Estimación: el par de la carga se calcula con los brazos reales (nodos cinemáticos) y " +
                "los pares nominales, con masas y factor de seguridad. Es una estimación de ingeniería.",
                "Schätzung: das Lastmoment folgt aus den echten Hebelarmen (Kinematikknoten) und den " +
                "Nennmomenten, inkl. Gliedmassen und Sicherheitsfaktor. Technische Schätzung.",
                "Estimation : le couple de charge vient des bras réels (nœuds cinématiques) et des " +
                "couples nominaux, avec masses et coefficient de sécurité. Estimation d'ingénierie.",
                "推定：負荷トルクは実際のリンク腕（運動学ノード）と関節定格トルクから計算し、" +
                "リンク質量と安全率を考慮します。計画用の工学推定です。"),
            Row("cmd.payload.tab",
                "Калькулятор нагрузки", "Payload calculator", "负载计算器", "Calculadora de carga",
                "Nutzlast-Rechner", "Calculateur de charge", "ペイロード計算"),
            Row("cmd.payload.tab.desc",
                "Максимальная нагрузка в текущей позе и график зависимости от расстояния от базы",
                "Max payload in the current pose and payload-vs-distance graph",
                "当前姿态的最大负载及负载-距离曲线",
                "Carga máxima en la pose actual y gráfico de distancia",
                "Max. Nutzlast in der aktuellen Pose und Abstandsdiagramm",
                "Charge max. dans la pose actuelle et courbe selon la distance",
                "現在の姿勢での最大ペイロードと距離グラフ"),

            // ---------------------------------------------------------- ЭТАП 11: языки роботов
            Row("export.title",
                "Экспорт траектории в язык робота", "Export trajectory to a robot language",
                "将轨迹导出为机器人语言", "Exportar trayectoria al lenguaje del robot",
                "Bahn in Roboter-Sprache exportieren", "Exporter la trajectoire en langage robot",
                "軌道をロボット言語へ書き出す"),
            Row("export.language",
                "Язык робота", "Robot language", "机器人语言", "Lenguaje del robot",
                "Robotersprache", "Langage du robot", "ロボット言語"),
            Row("export.lang.krl",
                "KUKA KRL", "KUKA KRL", "KUKA KRL", "KUKA KRL", "KUKA KRL", "KUKA KRL", "KUKA KRL"),
            Row("export.lang.karel",
                "FANUC KAREL", "FANUC KAREL", "FANUC KAREL", "FANUC KAREL", "FANUC KAREL",
                "FANUC KAREL", "FANUC KAREL"),
            Row("export.lang.rapid",
                "ABB RAPID", "ABB RAPID", "ABB RAPID", "ABB RAPID", "ABB RAPID", "ABB RAPID",
                "ABB RAPID"),
            Row("export.button",
                "Экспорт траектории", "Export trajectory", "导出轨迹", "Exportar trayectoria",
                "Bahn exportieren", "Exporter la trajectoire", "軌道を書き出す"),
            Row("export.done",
                "файл создан", "file created", "文件已创建", "archivo creado", "Datei erstellt",
                "fichier créé", "ファイルを作成しました"),
            Row("export.fail",
                "экспорт не выполнен", "export failed", "导出失败", "exportación fallida",
                "Export fehlgeschlagen", "échec de l'export", "書き出しに失敗"),
            Row("export.noplan",
                "Нет траектории: выберите точку (Z + ЛКМ) и подтвердите вариант (X + ЛКМ)",
                "No trajectory: pick a point (Z + LMB) and confirm a variant (X + LMB)",
                "无轨迹：请选点（Z + 左键）并确认方案（X + 左键）",
                "Sin trayectoria: elija un punto y confirme una variante",
                "Keine Bahn: Punkt wählen und Variante bestätigen",
                "Aucune trajectoire : choisissez un point et confirmez une variante",
                "軌道がありません：点を選び候補を確定してください"),
            Row("export.info",
                "Генерируется код движения по выбранной траектории: PTP (по суставам) и LIN " +
                "(линейные участки с ориентацией из прямой задачи). Файлы: trajectory.src (KUKA), " +
                "trajectory.kl (FANUC), trajectory.mod (ABB).",
                "Motion code for the selected trajectory is generated: PTP (joint) and LIN (linear " +
                "segments with orientation from forward kinematics). Files: trajectory.src (KUKA), " +
                "trajectory.kl (FANUC), trajectory.mod (ABB).",
                "为所选轨迹生成运动代码：PTP（关节）与 LIN（线性段，姿态由正解得出）。" +
                "文件：trajectory.src（KUKA）、trajectory.kl（FANUC）、trajectory.mod（ABB）。",
                "Se genera el código de movimiento: PTP (por ejes) y LIN (tramos lineales con orientación " +
                "de la cinemática directa). Archivos: trajectory.src / .kl / .mod.",
                "Es wird Bewegungs-Code erzeugt: PTP (Achsen) und LIN (lineare Abschnitte mit Orientierung " +
                "aus der Vorwärtskinematik). Dateien: trajectory.src / .kl / .mod.",
                "Le code de mouvement est généré : PTP (axes) et LIN (segments linéaires avec orientation " +
                "issue de la cinématique directe). Fichiers : trajectory.src / .kl / .mod.",
                "選択した軌道の動作コードを生成します：PTP（関節）と LIN（直線区間、姿勢は順運動学から）。" +
                "ファイル：trajectory.src／.kl／.mod。"),
            Row("export.folder",
                "Папка экспорта", "Export folder", "导出文件夹", "Carpeta de exportación",
                "Exportordner", "Dossier d'export", "書き出しフォルダ"),
            Row("cmd.export.robot",
                "Экспорт в язык робота", "Export to robot language", "导出为机器人语言",
                "Exportar al lenguaje del robot", "In Robotersprache exportieren",
                "Exporter en langage robot", "ロボット言語へ書き出し"),
            Row("cmd.export.robot.desc",
                "Код движения по выбранной траектории: KUKA KRL (.src), FANUC KAREL (.kl), ABB RAPID (.mod)",
                "Motion code for the selected trajectory: KUKA KRL (.src), FANUC KAREL (.kl), ABB RAPID (.mod)",
                "所选轨迹的运动代码：KUKA KRL（.src）、FANUC KAREL（.kl）、ABB RAPID（.mod）",
                "Código de movimiento: KUKA KRL (.src), FANUC KAREL (.kl), ABB RAPID (.mod)",
                "Bewegungs-Code: KUKA KRL (.src), FANUC KAREL (.kl), ABB RAPID (.mod)",
                "Code de mouvement : KUKA KRL (.src), FANUC KAREL (.kl), ABB RAPID (.mod)",
                "動作コード：KUKA KRL（.src）・FANUC KAREL（.kl）・ABB RAPID（.mod）"),
            Row("cmd.export.lang",
                "Язык экспорта (KRL / KAREL / RAPID)", "Export language (KRL / KAREL / RAPID)",
                "导出语言（KRL / KAREL / RAPID）", "Lenguaje de exportación",
                "Exportsprache (KRL / KAREL / RAPID)", "Langage d'export",
                "書き出し言語（KRL / KAREL / RAPID）"),
            Row("cmd.export.lang.desc",
                "Переключить язык робота для экспорта траекторий",
                "Switch the robot language used for trajectory export",
                "切换轨迹导出所用的机器人语言",
                "Cambiar el lenguaje usado al exportar",
                "Robotersprache für den Export wechseln",
                "Changer le langage utilisé pour l'export",
                "書き出しに使うロボット言語を切り替え"),

            // ---------------------------------------------------------- ЭТАП 12: импорт моделей
            Row("import.title",
                "Импорт модели робота (URDF / STEP)", "Robot model import (URDF / STEP)",
                "机器人模型导入（URDF / STEP）", "Importar modelo (URDF / STEP)",
                "Robotermodell importieren (URDF / STEP)", "Importer un modèle (URDF / STEP)",
                "ロボットモデルのインポート（URDF / STEP）"),
            Row("import.folder",
                "Папки поиска", "Search folders", "搜索文件夹", "Carpetas de búsqueda",
                "Suchordner", "Dossiers de recherche", "検索フォルダ"),
            Row("import.refresh",
                "Обновить список файлов", "Refresh file list", "刷新文件列表",
                "Actualizar la lista", "Dateiliste aktualisieren", "Actualiser la liste",
                "ファイル一覧を更新"),
            Row("import.load",
                "Импортировать", "Import", "导入", "Importar", "Importieren", "Importer", "インポート"),
            Row("import.none",
                "Файлы не найдены: положите .urdf или .step в папку поиска",
                "No files found: put a .urdf or .step into a search folder",
                "未找到文件：请将 .urdf 或 .step 放入搜索文件夹",
                "Sin archivos: coloque un .urdf o .step en la carpeta",
                "Keine Dateien: .urdf oder .step in den Ordner legen",
                "Aucun fichier : placez un .urdf ou .step dans le dossier",
                "ファイルがありません：.urdf か .step をフォルダに置いてください"),
            Row("import.done",
                "модель импортирована", "model imported", "模型已导入", "modelo importado",
                "Modell importiert", "modèle importé", "モデルをインポートしました"),
            Row("import.structure",
                "структура: база, звеньев {0}, суставов {1}, TCP",
                "structure: base, {0} links, {1} joints, TCP",
                "结构：基座、{0} 个连杆、{1} 个关节、TCP",
                "estructura: base, {0} eslabones, {1} ejes, TCP",
                "Struktur: Basis, {0} Glieder, {1} Gelenke, TCP",
                "structure : base, {0} liens, {1} axes, TCP",
                "構造：ベース・リンク {0}・関節 {1}・TCP"),
            Row("import.check",
                "Проверить кинематику", "Check kinematics", "检查运动学", "Comprobar la cinemática",
                "Kinematik prüfen", "Vérifier la cinématique", "運動学を検査"),
            Row("import.check.ok",
                "кинематика в порядке: FK-ошибка {0} мм, IK-ошибка {1} мм",
                "kinematics OK: FK error {0} mm, IK error {1} mm",
                "运动学正常：FK 误差 {0} mm，IK 误差 {1} mm",
                "cinemática correcta: error FK {0} mm, IK {1} mm",
                "Kinematik in Ordnung: FK-Fehler {0} mm, IK-Fehler {1} mm",
                "cinématique OK : erreur FK {0} mm, IK {1} mm",
                "運動学は正常：FK 誤差 {0} mm、IK 誤差 {1} mm"),
            Row("import.check.dof",
                "осей {0} · валидатор проекта поддерживает 6 (проверена прямая задача)",
                "axes {0} · the project validator supports 6 (forward kinematics checked)",
                "轴数 {0} · 项目验证器支持 6（已检查正解）",
                "ejes {0} · el validador admite 6 (se comprobó la cinemática directa)",
                "Achsen {0} · der Projektprüfer unterstützt 6 (Vorwärtskinematik geprüft)",
                "axes {0} · le validateur accepte 6 (cinématique directe vérifiée)",
                "軸数 {0} · 検証器は 6 対応（順運動学を確認）"),
            Row("import.remove",
                "Удалить импортированного робота", "Remove imported robot", "删除导入的机器人",
                "Eliminar el robot importado", "Importierten Roboter entfernen",
                "Supprimer le robot importé", "インポートしたロボットを削除"),
            Row("import.step.stub",
                "STEP: базовая поддержка — геометрия прочитана (габарит {0} м), кинематическое " +
                "дерево в STEP не описано, поэтому создан только визуальный корпус",
                "STEP: basic support — geometry read (extent {0} m); STEP has no kinematic tree, so " +
                "only a visual body was created",
                "STEP：基础支持——已读取几何（尺寸 {0} m）；STEP 无运动学树，仅创建可视本体",
                "STEP: soporte básico — geometría leída ({0} m); STEP no tiene árbol cinemático",
                "STEP: Basisunterstützung — Geometrie gelesen ({0} m); STEP hat keinen Kinematikbaum",
                "STEP : support de base — géométrie lue ({0} m) ; pas d'arbre cinématique",
                "STEP：基本対応 — 形状を読み取り（{0} m）。運動学ツリーは無いため表示のみ作成"),
            Row("import.info",
                "URDF читается с диска (папки поиска + StreamingAssets/robots), структура создаётся " +
                "кодом: база → звенья → суставы (revolute/prismatic с лимитами) → TCP. Импортированный " +
                "робот — самостоятельный объект сцены, его можно удалить.",
                "URDF is read from disk (search folders + StreamingAssets/robots) and the structure is " +
                "built in code: base → links → joints (revolute/prismatic with limits) → TCP. The " +
                "imported robot is a standalone scene object and can be removed.",
                "URDF 从磁盘读取（搜索文件夹 + StreamingAssets/robots），结构由代码创建：基座→连杆→关节→TCP。" +
                "导入的机器人是独立对象，可删除。",
                "El URDF se lee del disco y la estructura se crea en código: base → eslabones → ejes → TCP. " +
                "El robot importado es un objeto independiente y se puede eliminar.",
                "URDF wird von der Platte gelesen, die Struktur im Code aufgebaut: Basis → Glieder → " +
                "Gelenke → TCP. Der importierte Roboter ist ein eigenständiges Objekt.",
                "L'URDF est lu sur le disque et la structure est créée par code : base → liens → axes → TCP. " +
                "Le robot importé est un objet autonome.",
                "URDF をディスクから読み、構造をコードで生成：ベース→リンク→関節→TCP。" +
                "インポートしたロボットは独立したオブジェクトです。"),
            Row("cmd.import.tab",
                "Импорт модели робота", "Robot model import", "机器人模型导入",
                "Importar modelo de robot", "Robotermodell importieren",
                "Importer un modèle de robot", "ロボットモデルのインポート"),
            Row("cmd.import.tab.desc",
                "Загрузить URDF (рабочая кинематика) или STEP (базовая поддержка) и проверить кинематику",
                "Load URDF (working kinematics) or STEP (basic support) and check the kinematics",
                "加载 URDF（可用运动学）或 STEP（基础支持）并检查运动学",
                "Cargar URDF (cinemática funcional) o STEP (soporte básico) y comprobar la cinemática",
                "URDF (funktionsfähige Kinematik) oder STEP (Basis) laden und Kinematik prüfen",
                "Charger un URDF (cinématique fonctionnelle) ou STEP (support de base) et vérifier",
                "URDF（動作する運動学）または STEP（基本対応）を読み込み、運動学を検査"),
        };

        private static string[] Row(string key, string ru, string en, string zh, string es,
            string de, string fr, string ja)
        {
            return new[] { key, ru, en, zh, es, de, fr, ja };
        }
    }
}
